language: node_js
node_js:
  - "lts/*"
before_script:
  - echo $(TRAVIS_BRANCH)
  - echo $(TRAVIS_PULL_REQUEST_BRANCH)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
branches:
  only:
    - master
    - /fix\/.+/
    - /feature\/.+/
after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage.lcov
  - ./cc-test-reporter upload-coverage
