name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    name: build / node ${{ matrix.node }} / ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - name: Restore dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2-preview
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: binaries
          path: ./dist

  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    name: test / node ${{ matrix.node }} / ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - name: Restore dependencies
        run: npm ci

      - name: Test library
        if: matrix.platform != 'ubuntu-latest'
        run: npm run test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: matrix.platform == 'ubuntu-latest'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          executable: ./cc-test-reporter
          coverageCommand: npm run coverage
          coverageLocations: ./coverage/clover.xml:clover
